Syntax 3

Comment "Librem 5 Built-in Audio"


SectionUseCase."HiFi" {
	File "HiFi.conf"
	Comment "Default"
}

BootSequence [
	cset "name='Digital Playback Volume' 96,96" # 0dB
	cset "name='Digital Capture Volume' 96,96" # 0dB
	cset "name='Speaker Volume' 121,121" # 0dB
	cset "name='Speaker Boost Volume' 2" # 3dB
	cset "name='Headphone Volume' 121,121" # 0dB
	cset "name='Headphone Aux Volume' 1" # -6dB
	cset "name='Capture Volume' 31,31" # 0dB
	cset "name='MIXINL PGA Volume' 0" # 0dB
]
